- docs/Git・GitHub運用方針.md
> docs: 📄 Git・Githubの運用ドキュメントの作成

- package-lock.json
- src/App.jsx
- src/SignUp.jsx
- src/firebaseConfig.js
このPRでは、Firebase Authenticationを使用してサインアップ機能を実装しました。
ユーザーはメールアドレスとパスワードで登録できるようになっています。
今後はログイン機能の実装を予定しています。
> Firebase認証機能の実装（サインアップ）

- server.js
> server.jsの追加

- package-lock.json
- package.json
nodemonで起動できるようにしました。
例：nodemon server.js
> feat: nodemonを導入

- src/firebaseConfig.js
> feat: Firestoreのセットアップを追加

- src/pages/auth/SignIn.jsx
- src/pages/auth/SignUp.jsx
Closes #43 
- サインイン、サインアップ処理の際のローディングの実装
- 
- 
-
> feature #43: サインイン、サインアップ処理の際のローディングの実装

- package-lock.json
- package.json
- src/pages/chatpage/ChatPage.css
- src/pages/chatpage/ChatPage.jsx
- src/pages/chatpage/SendMessage.jsx
> #17 chat page 

- package-lock.json
- src/App.jsx
- src/pages/chatpage/SendMessage.jsx
チャットリストの画面とチャットの画面へのルーティングが書かれていなかったので、修正しました。
該当するページのファイルも一部修正しました。
また、それにともない必要なパッケージなどのインストールなども行っています。
> fix: ルーティングの修正

- src/pages/chatpage/ChatPage.jsx
- src/pages/chatpage/SendMessage.jsx
firebaseとチャットを連携しました。
また、スタイルを修正しました。
> feat: チャット機能の実装とデータベース連携、スタイルの修正

- src/pages/auth/SignIn.jsx
- src/pages/auth/SignUp.jsx
> feature #54: firebase auth関連のエラーを日本語化 & バリデーションチェックの実装

- src/components/NavigationBar.jsx
- src/components/SnackbarComponent.jsx
- src/styles/navbarStyles.js
> style #56:BottomNavBarのデザインの編集

- src/firebaseConfig.js
> chore: update firebase config to use environment variables

- src/App.jsx
> fix: roting

- src/components/NavigationBar.jsx
- src/pages/chats/ChatListPage.jsx
- src/pages/chats/FriendList.jsx
> ユーザー固有のフレンドリスト取得機能を実装

- src/components/NavigationBar.jsx
- src/hooks/useAuth.jsx
- src/pages/chats/ChatListPage.jsx
- src/pages/chats/FriendList.jsx
- src/pages/chats/GroupList.jsx
- src/styles/chatlistpageStyles.js
> Feature/#49 #10 update chat screen UI and connect with firestore

- src/pages/chats/ChatListPage.jsx
> fix: 不要なパッケージを削除

- src/create_event/create_event.js
> feat: イベント簡易生成API作成(UI未完成)

- src/pages/auth/SignIn.jsx
- src/pages/auth/SignUp.jsx
> feat: fix_UI

- package-lock.json
- src/pages/user/UserAttributesPage.jsx
> feat: test_vite

- index.html
> refac: site_name_change

- src/pages/user/ProfilePage.jsx
Closes #104 
[https://developers.google.com/maps/documentation/javascript/places](url)
- プロフィールページで場所選択機能が動作しない問題を修正
- 現在地周辺の地域を自動取得する機能を追加
- 地域選択時に都道府県、市区町村、区などの詳細な地域名を表示するように改善
- 選択した地域の削除機能を実装
- ローディング表示とエラーハンドリングを追加
- 全国の地域を検索する機能（今回は現在地周辺のみ）
- 選択可能な地域数の制限
- 地域の重複チェック
- プロフィール画面での場所選択機能の動作
- 現在地周辺の地域が正しく表示されること
- 地域選択時に正しい地域名が表示されること
- 選択した地域の削除が正常に動作すること
- プロフィール保存時にデータが正しく保持されること
- 位置情報を無効にしている場合の動作
- Google Places APIの制限に達した場合の動作
- 通信速度が遅い環境での動作
- Google Places APIの使用制限に注意が必要
- 位置情報の取得にはユーザーの許可が必要
> fix: プロフィール画面の場所選択機能を修正

- src/pages/chatpage/GroupChatPage.jsx
- src/pages/events/api/googlePlacesApi.js
- src/pages/events/services/eventGenerator.js
- src/pages/events/services/storeSelector.js
- src/pages/events/tests/EventGenerationTest.jsx
- src/pages/events/utils/timeUtils.js
- src/pages/user/ProfilePage.jsx
- src/pages/user/TimeAndLocationPage.jsx
Closes #114 
- イベント生成機能の追加および周辺店舗検索の実装
- このプルリクエストでは、グループチャットページへのイベント生成機能の導入、Google Places API を利用した店舗検索および詳細情報取得機能を追加し、関連するコードのリファクタリングを行いました。以下に主な変更点を記載します。
- 主な変更点
1.	EventGenerationTestコンポーネントの追加
•	イベント生成機能をテストするためのコンポーネントをグループチャットページに導入しました。
•	プリセットのタイムスロットとグループIDに基づいてイベントを生成します。
2.	Google Places API 統合
•	googlePlacesApi.js を新規作成し、周辺店舗検索および詳細情報の取得機能を実装しました。
•	キャッシュを利用してパフォーマンスを向上させ、APIリクエストとレスポンスにエラーハンドリングとロギングを追加しました。
3.	ストア選択ロジックの実装
•	storeSelector.js に selectStore 関数を追加し、グループメンバーの好みや利用可能時間に基づいて店舗を選択する機能を実装しました。
•	店舗評価やレビューに基づいたスコアリング機能を導入しました。
4.	タイムユーティリティ関数の追加
•	timeUtils.js を作成し、営業時間のバリデーションやタイムスロット管理を行う機能を実装しました。
•	営業時間やビジネスステータスが不足している場合のハンドリングを強化しました。
5.	コードリファクタリング
•	未使用のインポートや不要なコンソールログを削除してコードを簡潔化しました。
•	onSnapshot ロジックを改善し、読みやすさとエラーハンドリングを向上させました。
6.	デバッグ用ロギングの追加
• …
> feat/#114: 飲み会イベントをユーザーの情報を使って自動で生成させる機能の実装

- src/pages/chatpage/GroupChatPage.jsx
- src/pages/events/components/GroupEventDetail.jsx
- src/pages/events/components/GroupEventPreview.jsx
- src/pages/events/services/eventGenerator.js
- src/pages/events/services/storeSelector.js
- src/pages/events/tests/EventGenerationTest.jsx
- src/styles/navbarStyles.js
Closes #115 
**グループチャットページにおけるイベント管理機能の強化**
このプルリクエストでは、グループチャットページにイベント管理機能を統合し、UI/UXの改善やコードのリファクタリングを行いました。また、イベント生成や表示に関連する新しいコンポーネントを追加し、ストア選択ロジックやエラーハンドリングを強化しました。
- グループチャットページにイベント取得・生成機能を追加。  
- ローディング状態管理やイベントの展開/折りたたみ機能を実装しました。  
- **GroupEventDetail**  
- イベントの詳細情報を表示するコンポーネント。  
- 参加者情報やアクションボタン（参加/詳細閉じる）を実装。  
- **GroupEventPreview**  
- イベントの概要を表示するコンポーネント。  
- ホバー効果やアイコンを活用したインタラクティブなデザインを提供。  
- イベントのロケーション管理を強化するため、Google Maps API の初期化とエラーハンドリングを追加しました。  
- ストア情報の必須フィールドチェックやエラーハンドリングを導入。  
- フォーマット済み住所の優先取得やデフォルト値の設定により、データ処理の堅牢性を向上。  
- 生成したイベントデータをFirestoreに保存する機能を追加。  
- メッセージ入力およびイベント表示セクションをリファクタリングし、視認性と操作性を向上。  
- Material-UI コンポーネントを活用したレスポンシブなデザインを実現。  
- ナビバーの背景色を透明化し、全体のデザインを統一しました。  
- イベント生成やストア選択プロセスにおける詳細なロギングを追加し、デバッグ効率を向上させました。  
- …
> feat/#115: 自動生成された飲み会イベントがグループ画面に表示されるように実装

- src/components/friends/AddFriendModal.jsx
- src/components/groups/CreateGroupModal.jsx
- src/pages/chatpage/ChatPage.jsx
- src/pages/chatpage/GroupChatPage.jsx
- src/pages/chats/ChatListPage.jsx
- src/pages/chats/FriendList.jsx
- src/pages/chats/GroupList.jsx
- src/pages/events/components/GroupEventDetail.jsx
- src/pages/events/components/GroupEventPreview.jsx
- src/styles/theme.js
> feat/#123: 全体的なコンポーネントのUI改善

- src/App.jsx
- src/components/Loading/BeerLoader.jsx
- src/components/Loading/BeerLoader.module.css
- src/components/friends/AddFriendModal.jsx
- src/components/groups/CreateGroupModal.jsx
- src/components/search/SearchDialog.jsx
- src/contexts/LoadingContext.jsx
- src/firebaseConfig.js
- src/pages/chats/ChatListPage.jsx
- src/pages/chats/FriendList.jsx
- src/pages/chats/GroupList.jsx
- src/services/onlineStatus.js
- src/utils/dateUtils.js
**アプリケーションのオンラインステータス管理とロード状態改善機能を実装**  
このプルリクエストでは、オンラインステータス管理機能やロード状態管理機能を統合し、UI/UXの向上を図りました。また、グループや友人リストのUI改善、検索機能の強化など、全体的なコード構造のリファクタリングを行いました。
---
- **Firebase Realtime Database** を使用してユーザーのオンライン/オフライン状態を追跡。  
- **disconnect 時の自動ステータス更新** を実装（例: オフラインとタイムスタンプを記録）。  
- リアルタイムでオンライン状態を表示する機能を**FriendList**や**GroupList**に統合。
---
- **LoadingContext** を導入し、アプリ全体で一貫性のあるロード状態を管理。  
- ローディング時に表示する**BeerLoader コンポーネント**を新規作成。  
- カスタムアニメーションを実装し、視覚的なフィードバックを強化。  
---
- ローディング状態にカスタムローダーを追加し、データ取得中のUXを改善。  
- **Material-UI** を活用し、タイポグラフィやホバー効果を改善。  
- アバターやチップのスタイルを更新し、モダンで一貫性のあるデザインを提供。  
- **検索機能の強化**  
- 入力スタイルや検索結果のレイアウトを改良し、視認性を向上。  
- 検索中のロード状態を反映するカスタムローダーを追加。  
---
- **dateUtils.js** を新規作成し、日本語で相対時間を表示する機能を提供。  
- `dayjs` を使用して日付操作とローカリゼーションを実装。  
---
- Firebase Realtime Database …
> feat: グループ作成モーダルにユーザー検索機能の追加 + αの新機能実装

- src/components/Header.jsx
- src/hooks/useAuth.jsx
- src/services/onlineStatus.js
Closes #127 
- onlineStatus.js: ログアウト時にユーザーのオンラインステータスを確実にオフラインに設定するためのクリーンアップ処理を追加
- useAuth.jsx: signOut関数を追加し、ログアウト時にオンラインステータスをクリーンアップするように修正
- Header.jsx: ログアウトボタンでuseAuthのsignOut関数を使用するように変更
- 
- 
-
> fix/#127: ログアウト時にオンラインステータスがオフラインにならない問題を修正

- package-lock.json
- package.json
- src/services/eventService.ts
- src/services/notification.ts
- src/types/react-onesignal.d.ts
- src/utils/dateTimeUtils.js
- src/utils/locationUtils.js
- src/utils/venueUtils.js
#130 
Closes #
OneSignalの初期化機能を実装しました。
イベント通知を送信するための関数を追加しました。
位置情報を基に中央の位置を計算するユーティリティ関数を仮で作成しました。
近くの会場を検索するためのユーティリティ関数を仮で作成しました。
最適な日時を計算するためのユーティリティ関数を仮で作成しました。
- 
OneSignalの実際の通知送信機能のテストは行っていません。
UIとの統合は行っていません。
- 
開発環境: ローカル環境
ブラウザ: Firefox
- 
-
> feat: Implement OneSignal notification setup

- src/services/notifications/oneSignal.js
> refactor: 🛠️ プロンプトオプションを削除して origin とサブドメインの設定を追加。初期化失敗時には null を返す代わりにエラーをスローするよう変更

- src/services/notifications/oneSignal.js
> chore: 本番環境と開発環境でoriginを分けていたが、一旦開発環境に統一
